### ISSUE TITLE
Calibrate accelerometer

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#1]
Implement accelerometer calibration using Gauss-Newton method

Read more:
https://chionophilous.wordpress.com/2011/10/24/accelerometer-calibration-iv-1-implementing-gauss-newton-on-an-atmega/

**Comment by DanielStenis** [comment]
* Use dedicated sampling task for this? 
* Store sampled values dynamically?

**Comment by adam-at-epsilon** [comment]
* "online" calibration could be done in the sensor task as long as the sensors task is able to service all sensors
* storing values dynamically could help to avoid allocating extra stack size that isn't needed during normal operation.

**Comment by adam-at-epsilon** [comment]
Note: check filtering settings of LSM303DLHC accelerometer.
