### ISSUE TITLE
Make receiver<->reference signal map typedef struct

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#102]
Make receiver<->reference signal map typedef struct which stores the reference signal range/limits. Do this so that it can be set by config program and so that it can be stored persistently in flash memory.

Perhaps make this a protobuf struct?

**Comment by superdupersvard** [comment]
#146

**Comment by DanielStenis** [comment]
Seems to work well. Closing this now.
