### ISSUE TITLE
Sensor x y z coordinate frames

### ISSUE THREAD

**Issue by adam-at-epsilon** [afconsult-south/dragonfly-fcb#107]
Determine how x, y and z axes are oriented for gyroscope, magnetometer and accelerometer, whether they are in agreement or need rotation before use.

**Comment by adam-at-epsilon** [comment]
The coordinate frame of our quadcopter fuselage is:

Positive x points forward between M1 and M2 arms.
Positive y becomes starboard.
Positive z is down.

**Comment by adam-at-epsilon** [comment]
Gyro & accelerometer analysed (they have their axes according to their respective datasheets, but not aligned)

In progress.

**Comment by adam-at-epsilon** [comment]
![coordinateframes](https://cloud.githubusercontent.com/assets/12052828/9819419/36cd842a-58ae-11e5-8948-8d50a9506e2a.png)

**Comment by adam-at-epsilon** [comment]
The inclination of earth's magnetic field in Malmo is high, about 70 degrees.

The magnetometer shows positive values for magnetic north (cross-checked with actual compass).

http://gravmag.ou.edu/mag_earth/mag_earth.html

**Comment by adam-at-epsilon** [comment]
diagram now done ... under the assumption that I got the orientation of the STM32F3 board correct with respect to the body frame of the quadcopter. Did I, @DanielStenis ?

![coordinateframes](https://cloud.githubusercontent.com/assets/12052828/9833575/275c3466-599c-11e5-893a-b5e34c32f32d.png)

**Comment by adam-at-epsilon** [comment]
![](https://github.com/afconsult-south/dragonfly-fcb/blob/master/doc-latex/images/CoordinateFrames.png)

**Comment by adam-at-epsilon** [comment]
This is hopefully clear how the sensors are orientated with respect to the quadcopter body frame.

Is the STM32F3 orientation correctly depicted (i.e. the "diode circle" points ahead?)

![coordinateframes](https://cloud.githubusercontent.com/assets/12052828/9833637/80c4424e-599e-11e5-8b25-c0b6bdaadf58.png)

**Comment by adam-at-epsilon** [comment]
done with commit referenced just above. Diagram of coordinate frames added to wiki page "Sensors"

**Comment by DanielStenis** [comment]
Looks right! 

Maybe we could make an enum struct that makes it possible for us to redefine the coordinate system relative to the board?
