### ISSUE TITLE
Python tool for real-time plot of sensors & states

### ISSUE THREAD

**Issue by adam-at-epsilon** [afconsult-south/dragonfly-fcb#138]
This is useful for trimming the PID controller, validating the Kalman filter.

It is also useful as a demo tool.

It will be developed using Python 2.7.

**Comment by adam-at-epsilon** [comment]
A `PcFcbTool.py` file has been added to the Tools directory.

All it does is to ...
* open port COM8
* send the `about` command to FCB
* then print the output from FCB to console.

It's a work-in progress.

**Comment by adam-at-epsilon** [comment]
the tool now handles state parsing. It could/should be extended with the other kinds of protbuf serialised messages sent from FCB.

**Comment by DanielStenis** [comment]
Closing this issue as the project has moved to the dragonfly repository.
