### ISSUE TITLE
Migrate code to STM32CubeF3 library

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#15]
Current code is written for the old Std Peripheral Library, which is no longer maintained or recommended for new applications. 

Instead, the STM32Cube library is recommended.

Get acquainted with it and migrate old code to use the new library functions instead.

Perhaps even make use of the STM32CubeMX windows app, which help developers calculate clocks, prevent I/O conflicts and even does some auto-code generation of peripheral initialiation.

**Comment by DanielStenbergAF** [comment]
Commented out old code and made the program build and run on the board.

Gradually, the old Std Periph Lib code will be migrated (and improved).

Most of the motor control code has already been migrated.

**Comment by DanielStenis** [comment]
Motor control has been done.

Receiver code in progress (quite far along).

What remains?
Sensor reading
Control allocation

**Comment by DanielStenis** [comment]
Done. (Older code will be reused/replaced, commented out for now)
