### ISSUE TITLE
Limit vibrations on FCB board

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#154]
To limit the amount of sensor reading influence that vibrations cause to the FCB on-board sensors, the board must be attached such that these vibrations are attenuated.

This can be done in several different ways, some of which are presented here: http://ardupilot.org/copter/docs/common-vibration-damping.html

Perhaps an easy approach would be to buy ear plugs or some elastic gel/foam material and fasten below where the FCB is attached.

**Comment by superdupersvard** [comment]
Ear plugs and double-coated adhesive tape were used to reduce the vibrations on FCB. If the ear plugs were mounted in a vertical way it will mostly reduce vibration in x and y axis. During testing it was found out that when mounting the ear plugs at 45 degrease it will damp the vibration in all axis.
![dsc_0151](https://cloud.githubusercontent.com/assets/10959361/18001357/cac751aa-6b82-11e6-8cb0-12fa17f25d44.JPG)
