### ISSUE TITLE
Change IDE to Eclipse or other?

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#20]
CooCox is alright, but doesn't seem to be the most stable IDE and has rather messy configuration.

Perhaps consider another open-source IDE? Can we use Eclipse with GCC for ARM Toolchain with debugging and programming directly from the IDE?

**Comment by adam-at-epsilon** [comment]
I concur, if we can find a more stable and full-featured IDE in the future like eclipse it would be good.

**Comment by DanielStenbergAF** [comment]
GNU ARM Eclipse Plug-ins: http://sourceforge.net/projects/gnuarmeclipse/

These plug-ins provide build and debug extensions for Eclipse CDT (C/C++ Development Tools) for 32/64-bit GNU ARM toolchains like GNU Tools for Embedded, Linaro, etc, ready to run STM32Fx project templates and full integration for advanced J-Link JTAG/SWD probes, including SWO tracing console and peripheral registers view.

**Comment by DanielStenis** [comment]
I think we should consider getting GCC for ARM running with Eclipse soon as it would open up the possibility to work with the project in both Windows AND Linux OS.

https://launchpad.net/gcc-arm-embedded has a GCC ARM version for Linux

According to moderators on CooCox CoIDE forum, a Linux version of their IDE is currently not under development.

**Comment by DanielStenis** [comment]
More IDE options here: http://www.emcu.it/STM32/What_should_I_use_to_develop_on_STM32/What_should_I_use_to_develop_on_STM32.html

**Comment by DanielStenis** [comment]
For Linux, we must also consider ST-Link/V2 debugger support and drivers. So in summary we need:
- Compiler/linker/toolchain: GCC for ARM (has Win/Linux/Mac versions)
- IDE: Eclipse?
- Debugger drivers: Drivers exist for Windows. What are out alternatives for Linux?

**Comment by adam-at-epsilon** [comment]
Eclipse + OpenOCD + Windows

http://engineering-diy.blogspot.se/2012/12/stm32f3-discovery-on-windows-with.html

**Comment by DanielStenis** [comment]
http://gnuarmeclipse.livius.net/

**Comment by adam-at-epsilon** [comment]
Eclipse has an Egit plugin for git. This could be useful when refactoring our source tree.

http://www.eclipse.org/egit/

**Comment by DanielStenis** [comment]
Got GNU ARM Eclipse plugin to work for Eclipse CDT. Shouls be a possibility for both Windows and Linux OS.

Also got OpenOCD debugging working with the ST-Link in Eclipse.

See eclipse-migration-branch branch in repo.

**Comment by DanielStenis** [comment]
Using EGit at my home workstation. Works well it seems.

**Comment by DanielStenis** [comment]
Done.
