### ISSUE TITLE
Redo motor control<->thrust force mapping

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#39]
Since the HAL driver migration, modifications have been made on how to control the motor control pulse. This means the motor pulse <-> thrust mapping needs to be remade.

Plotly is an online line fitting tool useful here: https://plot.ly/plot

The motor thrust is controlled by a 16-bit int, values 0 to FFFF. Map this to generated thrust force [N] (see design document on ONE project site for some data on this)

**Comment by DanielStenbergAF** [comment]
https://plot.ly/~Stenis87/8

**Comment by DanielStenis** [comment]
Perhaps do a macro function for this.

**Comment by DanielStenis** [comment]
Done.
