### ISSUE TITLE
git branching strategy

### ISSUE THREAD

**Issue by adam-at-epsilon** [afconsult-south/dragonfly-fcb#44]
Wee need one to coordinate commits and which work is done on which branch.

**Comment by DanielStenis** [comment]
I agree. When we're a bit further along with the HAL Driver migration and RTOS perhaps we should consider merging to master and branching anew.

**Comment by adam-at-epsilon** [comment]
I think this issue can be closed now that I have updated the git workflow: https://github.com/afconsult-south/dragonfly-fcb/wiki/ToolTipsTricks#git-workflow
