### ISSUE TITLE
set compiler to use hardware floating point

### ISSUE THREAD

**Issue by adam-at-epsilon** [afconsult-south/dragonfly-fcb#57]
There's extra speed to be had according to [this Stackoverflow thread](http://stackoverflow.com/questions/3321468/whats-the-difference-between-hard-and-soft-floating-point-numbers) when using hard FPU instead of soft FPU.

This appears to involve using a libc using hard FPU beyond merely changing our compiler setting.

**Comment by DanielStenis** [comment]
This has been done ages ago! :D
