### ISSUE TITLE
Bugs in stm32f3_discovery.h regarding gyroscope interrupts

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#59]
Interrupt 1 (INT1) and Interrupt 2/Data ready (INT2/DRDY) pins and interrupt handlers seem to be all wrong. Correct these by studing the STM32F3DISCOVERY User Manual and STM32F3 Reference Manual.

It concerns the pin numbering, EXTI line and EXTI interrupt handlers.

**Comment by adam-at-epsilon** [comment]
I'll do it as soon as I have the gyro working properly.

**Comment by adam-at-epsilon** [comment]
pushed to master. ST Microelectronics responded in the forum they will fix it in future versions of STM32Cube
