### ISSUE TITLE
Use FreeRTOS to create thread

### ISSUE THREAD

**Issue by DanielStenbergAF** [afconsult-south/dragonfly-fcb#8]
Start introduction of an RTOS by simply creating a thread and see that it executes some simple instructions.

**Comment by adam-at-epsilon** [comment]
Done, adding FreeRTOS required adding the the xPortSysTickHandler to SysTick_Handler in fcb/fcb/src/stm32f3xx_it.c

Look at the [patch](https://github.com/afconsult-south/dragonfly-fcb/commit/b711aafe299125bc05c89e90b17f1b38d6545e38)
