### ISSUE TITLE
Debug print with SWO

### ISSUE THREAD

**Issue by DanielStenis** [afconsult-south/dragonfly-fcb#89]
It may be useful to enable debug printing with SWO interface instead of USB, since that is dependent on the USB working after system error.

In the GNU ARM Eclipse example project "Blinky", there is support for this.

A good thing for instance would be to print the HardFault handler message to this.

**Comment by khayyami** [comment]
This feature was added sep 1 2015. For printouts on console in debug mode use trace_printf()
Files:
trace.c
trace.h
trace_impl.c
trace_impl.h
semihosting.c
